ALTER TABLE players ADD COLUMN IF NOT EXISTS balance DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS frozen_balance DECIMAL(19,2) NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
