/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Theme-dependent tokens: values live in src/global.css as CSS variables,
        // served per color scheme at runtime by NativeWind.
        bp: {
          background: 'var(--bp-background)',
          bg: 'var(--bp-bg)',
          surface: 'var(--bp-surface)',
          surfaceAlt: 'var(--bp-surface-alt)',
          elevated: 'var(--bp-elevated)',
          borderInactive: 'var(--bp-border-inactive)',
          textPrimary: 'var(--bp-text-primary)',
          textSecondary: 'var(--bp-text-secondary)',
          textInactive: 'var(--bp-text-inactive)',
          surface60: 'var(--bp-surface-60)',
          // Text inks: bright brand colors get darker shades on the light theme
          goldInk: 'var(--bp-gold-ink)',
          accentInk: 'var(--bp-accent-ink)',
          warningInk: 'var(--bp-warning-ink)',
          dangerInk: 'var(--bp-danger-ink)',
          successInk: 'var(--bp-success-ink)',
          secondaryInk: 'var(--bp-secondary-ink)',
          border: 'var(--bp-border-inactive)',
          // Brand colors shared across themes
          borderActive: '#6B5BFF',
          primary: '#6B5BFF',
          primaryDisabled: '#3A357A',
          secondary: '#FFB454',
          accent: '#36E4B5',
          gold: '#F2C94C',
          warning: '#f2994a',
          success: '#27ae60',
          danger: '#FF5C6C',
          // Alpha-baked brand tints (invariant across themes)
          accent10: '#36E4B51A',
          accent40: '#36E4B566',
          borderActive40: '#6B5BFF66',
          danger10: '#FF5C6C1A',
          danger15: '#FF5C6C26',
          danger20: '#FF5C6C33',
          danger30: '#FF5C6C4D',
          danger40: '#FF5C6C66',
          danger50: '#FF5C6C80',
          danger60: '#FF5C6C99',
          gold10: '#F2C94C1A',
          gold20: '#F2C94C33',
          gold25: '#F2C94C40',
          gold30: '#F2C94C4D',
          gold40: '#F2C94C66',
          gold50: '#F2C94C80',
          gold60: '#F2C94C99',
          primary10: '#6B5BFF1A',
          primary15: '#6B5BFF26',
          primary20: '#6B5BFF33',
          primary30: '#6B5BFF4D',
          primary40: '#6B5BFF66',
          primary60: '#6B5BFF99',
          success10: '#27AE601A',
          success15: '#27AE6026',
          success30: '#27AE604D',
          success40: '#27AE6066',
          success60: '#27AE6099',
          warning10: '#F2994A1A',
          warning15: '#F2994A26',
          warning30: '#F2994A4D',
          warning40: '#F2994A66',
          warning60: '#F2994A99',
        },
      },
    },
  },
  plugins: [],
};